version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15
    container_name: wastesense-db
    environment:
      POSTGRES_DB: wastesense
      POSTGRES_USER: wastesense_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: wastesense-backend
    environment:
      - DATABASE_URL=postgresql://wastesense_user:${DB_PASSWORD}@database:5432/wastesense
      - PORT=3001
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - ML_SERVICE_URL=http://ml-service:8000
      - YOLO_API_URL=http://yolo-api:8001
    ports:
      - "3001:3001"
    depends_on:
      - database
    volumes:
      - ./backend/public:/app/public
    restart: unless-stopped

  # ML Forecasting Service
  ml-service:
    build:
      context: ./ml_service
      dockerfile: Dockerfile
    container_name: wastesense-ml
    environment:
      - PORT=8000
      - ENVIRONMENT=production
    ports:
      - "8000:8000"
    restart: unless-stopped

  # YOLO Waste Detection API
  yolo-api:
    build:
      context: ./wastesense-api/wastesense-api
      dockerfile: Dockerfile
    container_name: wastesense-yolo
    environment:
      - PORT=8001
      - ENVIRONMENT=production
    ports:
      - "8001:8001"
    volumes:
      - ./wastesense-api/wastesense-api/best.pt:/app/best.pt
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: wastesense-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - ml-service
      - yolo-api
    restart: unless-stopped

volumes:
  postgres_data: 